### ISSUE TITLE
Python 2 being deprecated in Fedora 33 (and probably in most distros soon)

### ISSUE THREAD

**Issue by somas95** [d3cod3/Mosaic#36] opened 2020-10-03 13:00 UTC
Python 2 is EOL and alredy being deprecated from most distros. Fedora 33, which will ship at the end of October, won't have it.

**Comment by d3cod3** [comment] 2020-10-03 23:19
[ofxPython](https://github.com/d3cod3/ofxPython) addon updated to python3.8 for linux boxes!

I'm closing this as the issue is solved.

**Closed as completed by d3cod3** 2020-10-03 23:19 UTC
